---
- name: Create and mount new storage
  hosts: all

  tasks:
         - name: Create new partition
           parted:
                  name: files
                  label: gpt
                  device: /dev/sda5
                  number: 1
                  state: present
                  part_start: 1MiB
                  part_end: 100MiB

         - name: Create xfs filesystem
           filesystem:
                  dev: /dev/sda5
                  fstype: xfs

         - name: Create mount directory
           file:
                  path: /data
                  state: directory
         - name: Mount the filesystem
           mount:
                  src: /dev/sda5
                  fstype: xfs
                  state: mounted

